# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zixiongliu/cube

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zixiongliu/cube

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zixiongliu/cube/CMakeFiles /Users/zixiongliu/cube/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zixiongliu/cube/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cube

# Build rule for target.
cube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cube
.PHONY : cube

# fast build rule for target.
cube/fast:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/build
.PHONY : cube/fast

cube.o: cube.cpp.o

.PHONY : cube.o

# target to build an object file
cube.cpp.o:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/cube.cpp.o
.PHONY : cube.cpp.o

cube.i: cube.cpp.i

.PHONY : cube.i

# target to preprocess a source file
cube.cpp.i:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/cube.cpp.i
.PHONY : cube.cpp.i

cube.s: cube.cpp.s

.PHONY : cube.s

# target to generate assembly for a file
cube.cpp.s:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/cube.cpp.s
.PHONY : cube.cpp.s

drawer.o: drawer.cpp.o

.PHONY : drawer.o

# target to build an object file
drawer.cpp.o:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/drawer.cpp.o
.PHONY : drawer.cpp.o

drawer.i: drawer.cpp.i

.PHONY : drawer.i

# target to preprocess a source file
drawer.cpp.i:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/drawer.cpp.i
.PHONY : drawer.cpp.i

drawer.s: drawer.cpp.s

.PHONY : drawer.s

# target to generate assembly for a file
drawer.cpp.s:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/drawer.cpp.s
.PHONY : drawer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/main.cpp.s
.PHONY : main.cpp.s

shader.o: shader.cpp.o

.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i

.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s

.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	$(MAKE) -f CMakeFiles/cube.dir/build.make CMakeFiles/cube.dir/shader.cpp.s
.PHONY : shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cube"
	@echo "... cube.o"
	@echo "... cube.i"
	@echo "... cube.s"
	@echo "... drawer.o"
	@echo "... drawer.i"
	@echo "... drawer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

